apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
  namespace: algorythmos-ai-agents
  labels:
    app: api-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-python
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
      - name: api-python
        image: algorythmos-ai-agents-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: REDIS_URL
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: API_PORT
        - name: SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: SMTP_SERVER
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: algorythmos-ai-agents-config
              key: SMTP_PORT
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: algorythmos-ai-agents-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: algorythmos-ai-agents-secrets
              key: ANTHROPIC_API_KEY
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: algorythmos-ai-agents-secrets
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: algorythmos-ai-agents-secrets
              key: SMTP_PASSWORD
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: algorythmos-ai-agents-secrets
              key: FROM_EMAIL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-python-service
  namespace: algorythmos-ai-agents
  labels:
    app: api-python
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: api-python
