apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay-clone-ingress
  namespace: relay-clone
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: relay-clone.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-python-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 3000
  - host: api.relay-clone.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-python-service
            port:
              number: 8000
